
package finalProject;

/**
 *
 * @author raphaelhicaro
 */
public class PokemonInfoWindow extends javax.swing.JFrame {
    private WeatherWindow weatherWin;
    private PokemonWindow pokemonWin;
    private PokemonInfoWindow pokeInfoWin;
    /**
     * Creates new form PokemonInfo
     */
    public PokemonInfoWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        pokeLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        lvlLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        pokeNameLabel = new javax.swing.JTextField();
        pokeImg = new javax.swing.JLabel();
        pokeTypeDesc = new javax.swing.JTextField();
        pokeLvlDesc = new javax.swing.JTextField();
        pokeDesc = new javax.swing.JTextField();
        returnBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Weathermon.png"))); // NOI18N

        pokeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokmon.png"))); // NOI18N

        typeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Type.png"))); // NOI18N

        lvlLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Level-Range.png"))); // NOI18N

        descLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Description.png"))); // NOI18N

        pokeNameLabel.setText("Pokemon Name");
        pokeNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokeNameLabelActionPerformed(evt);
            }
        });

        pokeImg.setText("Pokemon Picture");

        pokeTypeDesc.setText("Pokemon Type");
        pokeTypeDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokeTypeDescActionPerformed(evt);
            }
        });

        pokeLvlDesc.setText("lvl range");
        pokeLvlDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokeLvlDescActionPerformed(evt);
            }
        });

        pokeDesc.setText("Pokemon Description");

        returnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Return.png"))); // NOI18N
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pokeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pokeTypeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(typeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pokeLabel)
                            .addComponent(pokeImg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pokeLvlDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvlLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pokeDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnBtn)
                .addGap(174, 174, 174)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addComponent(returnBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lvlLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pokeLabel)
                        .addComponent(typeLabel)
                        .addComponent(descLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pokeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pokeTypeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pokeLvlDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pokeImg, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pokeDesc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setPokemonWin(PokemonWindow myCreator){
        pokemonWin = myCreator;
    }
    
    private void pokeNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokeNameLabelActionPerformed
    }//GEN-LAST:event_pokeNameLabelActionPerformed

    private void pokeTypeDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokeTypeDescActionPerformed
    }//GEN-LAST:event_pokeTypeDescActionPerformed

    private void pokeLvlDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokeLvlDescActionPerformed
    }//GEN-LAST:event_pokeLvlDescActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        pokemonWin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new PokemonInfoWindow().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel lvlLabel;
    private javax.swing.JTextField pokeDesc;
    private javax.swing.JLabel pokeImg;
    private javax.swing.JLabel pokeLabel;
    private javax.swing.JTextField pokeLvlDesc;
    private javax.swing.JTextField pokeNameLabel;
    private javax.swing.JTextField pokeTypeDesc;
    private javax.swing.JButton returnBtn;
    private javax.swing.JLabel title;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
